name: Docker

on:
  workflow_dispatch:
  push:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log Branch Name
        run: |
          echo running on branch ${GITHUB_REF##*/}
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        run: yarn install

      - name: Build
        env:
          APP_ENV: ${{ env.branch == 'master' && 'prod' || 'dev' }}
        run: yarn build

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for UI
        id: meta_ui
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,suffix=-${{ env.branch }}
#            type=ref,event=branch
#            type=ref,event=pr

      - name: Record Image Tags and Labels
        run: |
          echo "${{ steps.meta_ui.outputs.tags }}" >> 'image_tags'

      - uses: actions/upload-artifact@v3
        with:
          name: image_tags
          path: ./image_tags

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for UI
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_ui.outputs.tags }}
          labels: ${{ steps.meta_ui.outputs.image_labels }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Image Tags
        uses: actions/download-artifact@v3
        with:
          name: image_tags

      - name: Log Deploy
        run: |
          echo Deploying
          echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          echo ${{ env.image_tags }}
          cat image_tags
        
