name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ develop, release ]
    # Publish semver tags as releases.
    tags: [ "v*.*.*" ]

jobs:
  dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    env:
      ENV_NAME: dev
    steps:
      - name: Build in dev
        run:
          echo ${ENV_NAME}
  release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    env:
      ENV_NAME: prod
    steps:
      - name: Build in prod
        run: |
          echo ${ENV_NAME}
          echo ${{github.repo}}
  prod:
    if: contains( github.ref,'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Build in prod
        run: |
          echo ${{github.ref}}
          echo ${{github.ref_name}}
          echo ${{github.base_ref}}
          echo ${{github.base_ref}}
          echo 123
