name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: [ master, develop, ci-cd-configs, release ]
    # Publish semver tags as releases.
    tags: [ "v*.*.*" ]


jobs:
  dev_build:
    runs-on: ubuntu-latest
    steps:
      - name: Build in dev
        env:
          DEV_ENV_NAME: dev
        run:
          echo ${DEV_ENV_NAME}

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ contains( fromJson('${GITHUB_REF#refs/heads/}'), 'release' ) }}

      - run: echo ${GITHUB_REF#refs/heads/}

