name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ develop, release ]
    # Publish semver tags as releases.
    tags: [ "v*.*.*" ]

env:
  MODE: ${{ github.ref == 'refs/heads/develop' && "test" || github.ref == 'refs/heads/release' && "staging" || contains( github.ref,'refs/tags') && "prod" }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo ${MODE}