name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ develop, release ]
    tags: [ "v*.*.*" ]

env:
  MODE: ${{ github.ref == 'refs/heads/develop' && 'test' || github.ref == 'refs/heads/release' && 'staging' || contains( github.ref,'refs/tags') && 'prod' }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build in dev
        run:
          echo ${ENV_NAME}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for UI
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            ${{ env.MODE == 'prod' && 'type=semver,pattern=v{{version}}' || format('type=sha,suffix=-{0}',env.MODE) }}

      - run: |
          echo ${{ steps.meta.outputs.json }}
          echo ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
        name: echo


      - name: Build and push Docker image for UI
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.image_labels }}

      - name: Update ArgoCD Image
        uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 2.4.7
          command: app set ${{ github.event.repository.name }}-${{env.MODE}}
          options: |
            --server argocd.destill.io
            --kustomize-image ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
            --auth-token ${{ secrets.ARGOCD_TOKEN }}